### ISSUE TITLE
Random relocation of OSD elements

### ISSUE THREAD

**Issue by fabriciopolonio** [bri3d/msp-osd#19] opened 2022-06-07 22:24 UTC
When using the msp-osd, sometimes some of the OSD elements blink on the screen on top of other existing elements, for example:

Let's say on my OSD I have:

* Remaining battery (top)
* Craft name (left)
* Link Quality (left)

Sometimes the "Remaning battery" element for a short time is displayed on top of the "Link Quality" or the "Craft Name", then it goes back to its set position.

**Comment by bri3d** [comment] 2022-06-08 16:31
This is quite strange, I will look into seeing if I can reproduce this issue.

This is odd because MSP commands are processed command-wise and are checksummed. It's odd that drawing could happen in the wrong place.

I need to add a debugging functionality (which I have been working on as part of overlaying OSD in post-processing anyway) which will dump the MSP frames received by the goggles to figure out what could be going on here.

**Comment by fabriciopolonio** [comment] 2022-06-10 00:33
@bri3d if you need I can share my Betaflight OSD setup, in fact it happens in every flight I perform. Other than those small issues, working great, keep up the good work!

**Comment by DimitarKrastev** [comment] 2022-06-10 07:54
@fabriciopolonio Check your wiring. I started seeing this in the standard DJI goggles firmware with their stock limitted OSD. I started seeing the telemetry disappearing randomly for fraction of the second and random elements popping up in different parts of the screen. Even elements that I have not enabled like the bar battery indicator. This started happening on my last flight and I have crashed my drone a few times so I suspect something with the wiring.

**Comment by fabriciopolonio** [comment] 2022-06-13 13:10
Hi @DimitarKrastev, thanks for your suggestion, but this is not the situation I have here, my OSD works just fine with stock DJI OSD, cables are perfectly soldered and with no damage on them.

I think here there is only an issue with how the elements are rendered.

**Comment by bri3d** [comment] 2022-07-08 17:38
The latest version of msp-osd may help with this issue. Previously there was an issue where the byte stream could have ended up shifted by one byte, which may have led to the first or last message in a "frame" getting dropped randomly.

**Comment by bri3d** [comment] 2022-07-16 18:23
I think this should be fixed

**Closed as completed by bri3d** 2022-07-16 18:23 UTC
